### PR TITLE
Contact Book Pass 2

### PR DESCRIPTION
**Pull request by rtablada**
This is updates from an old branch on the guides-source before `tutorials` was broken out to a separate app.

This is getting close to a first draft where we can release:

1. Make raw HTML
2. Move HTML to raw template component 
3. Add attrs (both HTML and Ember assuming <AngleBracket />)
4. Move HBS to new list component
5. Make the list have array data and use an each loop
6. Make the list component load data from API async

To see this copy in action: https://deploy-preview-6--ember-tutorials.netlify.com/release/

After this we can get more iterative like @locks has discussed.

From there we would start doing:

* Move data loading to service (helper method organization)
* Make a form to create new items
* Use a service to manage data state
* Use routes to move logic to separate urls
* Dynamic routes

### CODE REVIEW

**Comment by rtablada** [comment]
Blocking:

* Change from ES6 Classes to Ember Object: `Foo.extend`

Possibly Blocking?:

* AngleBracket and `@attr`

**Comment by efx** [comment]
I'm starting on `Change from ES6 Classes to Ember Object: Foo.extend`. Also noticed it uses `constructor` which should be converted to `init`.

**Comment by efx** [comment]
@rtablada I opened the PR against `rtablada:rt/contact-book-v2updates` here: https://github.com/rtablada/tutorials/pull/1/files

**Comment by rtablada** [comment]
Closing in favor of #7 so that contributors can PR to the branch `contact-book` here instead of having to PR on my fork. Sorry @efx for any confusion.

**Comment by efx** [comment]
@mansona @rtablada got it, will try to get this later PM, eve.

**Pull request closed without merging**
